import SwiftUI
import CoreLocation

struct CountryLocation: Identifiable {
    let id = UUID()
    let name: String
    let code: String
    let coordinate: CLLocationCoordinate2D
}

let locations: [CountryLocation] = [
    CountryLocation(name: "Afghanistan", code: "AF", coordinate: CLLocationCoordinate2D(latitude: 33.93911, longitude: 67.709953)),
    CountryLocation(name: "Albania", code: "AL", coordinate: CLLocationCoordinate2D(latitude: 41.153332, longitude: 20.168331)),
    CountryLocation(name: "Algeria", code: "DZ", coordinate: CLLocationCoordinate2D(latitude: 28.033886, longitude: 1.659626)),
    CountryLocation(name: "Andorra", code: "AD", coordinate: CLLocationCoordinate2D(latitude: 42.5078, longitude: 1.5211)),
    CountryLocation(name: "Angola", code: "AO", coordinate: CLLocationCoordinate2D(latitude: -11.2027, longitude: 17.8733)),
    CountryLocation(name: "Antigua and Barbuda", code: "AG", coordinate: CLLocationCoordinate2D(latitude: 17.0608, longitude: -61.7964)),
    CountryLocation(name: "Argentina", code: "AR", coordinate: CLLocationCoordinate2D(latitude: -38.4161, longitude: -63.6167)),
    CountryLocation(name: "Armenia", code: "AM", coordinate: CLLocationCoordinate2D(latitude: 40.0691, longitude: 45.0382)),
    CountryLocation(name: "Australia", code: "AU", coordinate: CLLocationCoordinate2D(latitude: -25.2744, longitude: 133.7751)),
    CountryLocation(name: "Austria", code: "AT", coordinate: CLLocationCoordinate2D(latitude: 47.5162, longitude: 14.5501)),
    CountryLocation(name: "Azerbaijan", code: "AZ", coordinate: CLLocationCoordinate2D(latitude: 40.1431, longitude: 47.5769)),
    CountryLocation(name: "Bahamas", code: "BS", coordinate: CLLocationCoordinate2D(latitude: 25.0343, longitude: -77.3963)),
    CountryLocation(name: "Bahrain", code: "BH", coordinate: CLLocationCoordinate2D(latitude: 25.9304, longitude: 50.6378)),
    CountryLocation(name: "Barbados", code: "BB", coordinate: CLLocationCoordinate2D(latitude: 13.1939, longitude: -59.5432)),
    CountryLocation(name: "Belarus", code: "BY", coordinate: CLLocationCoordinate2D(latitude: 53.9, longitude: 27.5667)),
    CountryLocation(name: "Belgium", code: "BE", coordinate: CLLocationCoordinate2D(latitude: 50.5039, longitude: 4.4699)),
    CountryLocation(name: "Belize", code: "BZ", coordinate: CLLocationCoordinate2D(latitude: 17.1899, longitude: -88.4976)),
    CountryLocation(name: "Benin", code: "BJ", coordinate: CLLocationCoordinate2D(latitude: 9.3075, longitude: 2.3158)),
    CountryLocation(name: "Bhutan", code: "BT", coordinate: CLLocationCoordinate2D(latitude: 27.5142, longitude: 90.4336)),
    CountryLocation(name: "Bolivia", code: "BO", coordinate: CLLocationCoordinate2D(latitude: -16.2902, longitude: -63.5887)),
    CountryLocation(name: "Bosnia and Herzegovina", code: "BA", coordinate: CLLocationCoordinate2D(latitude: 43.9159, longitude: 17.6791)),
    CountryLocation(name: "Botswana", code: "BW", coordinate: CLLocationCoordinate2D(latitude: -22.3285, longitude: 24.6849)),
    CountryLocation(name: "Brazil", code: "BR", coordinate: CLLocationCoordinate2D(latitude: -14.235, longitude: -51.9253)),
    CountryLocation(name: "Brunei", code: "BN", coordinate: CLLocationCoordinate2D(latitude: 4.5353, longitude: 114.7277)),
    CountryLocation(name: "Bulgaria", code: "BG", coordinate: CLLocationCoordinate2D(latitude: 42.7339, longitude: 25.4858)),
    CountryLocation(name: "Burkina Faso", code: "BF", coordinate: CLLocationCoordinate2D(latitude: 12.2383, longitude: -1.5616)),
    CountryLocation(name: "Burundi", code: "BI", coordinate: CLLocationCoordinate2D(latitude: -3.3731, longitude: 29.9189)),
    CountryLocation(name: "Cabo Verde", code: "CV", coordinate: CLLocationCoordinate2D(latitude: 16.0020, longitude: -24.0132)),
    CountryLocation(name: "Cambodia", code: "KH", coordinate: CLLocationCoordinate2D(latitude: 12.5657, longitude: 104.9910)),
    CountryLocation(name: "Cameroon", code: "CM", coordinate: CLLocationCoordinate2D(latitude: 3.8480, longitude: 11.5021)),
    CountryLocation(name: "Canada", code: "CA", coordinate: CLLocationCoordinate2D(latitude: 56.1304, longitude: -106.3468)),
    CountryLocation(name: "Central African Republic", code: "CF", coordinate: CLLocationCoordinate2D(latitude: 6.6111, longitude: 20.9394)),
    CountryLocation(name: "Chad", code: "TD", coordinate: CLLocationCoordinate2D(latitude: 15.4542, longitude: 18.7322)),
    CountryLocation(name: "Chile", code: "CL", coordinate: CLLocationCoordinate2D(latitude: -35.6751, longitude: -71.5430)),
    CountryLocation(name: "China", code: "CN", coordinate: CLLocationCoordinate2D(latitude: 35.8617, longitude: 104.1954)),
    CountryLocation(name: "Colombia", code: "CO", coordinate: CLLocationCoordinate2D(latitude: 4.5709, longitude: -74.2973)),
    CountryLocation(name: "Comoros", code: "KM", coordinate: CLLocationCoordinate2D(latitude: -11.8750, longitude: 43.8722)),
    CountryLocation(name: "Congo", code: "CG", coordinate: CLLocationCoordinate2D(latitude: -0.2280, longitude: 15.8270)),
    CountryLocation(name: "Costa Rica", code: "CR", coordinate: CLLocationCoordinate2D(latitude: 9.7489, longitude: -83.7534)),
    CountryLocation(name: "Croatia", code: "HR", coordinate: CLLocationCoordinate2D(latitude: 45.1, longitude: 15.2)),
    CountryLocation(name: "Cuba", code: "CU", coordinate: CLLocationCoordinate2D(latitude: 21.5218, longitude: -77.7812)),
    CountryLocation(name: "Cyprus", code: "CY", coordinate: CLLocationCoordinate2D(latitude: 35.1264, longitude: 33.4299)),
    CountryLocation(name: "Czechia", code: "CZ", coordinate: CLLocationCoordinate2D(latitude: 49.8175, longitude: 15.4730)),
    CountryLocation(name: "Denmark", code: "DK", coordinate: CLLocationCoordinate2D(latitude: 56.2639, longitude: 9.5018)),
    CountryLocation(name: "Djibouti", code: "DJ", coordinate: CLLocationCoordinate2D(latitude: 11.8251, longitude: 42.5903)),
    CountryLocation(name: "Dominica", code: "DM", coordinate: CLLocationCoordinate2D(latitude: 15.4149, longitude: -61.3700)),
    CountryLocation(name: "Dominican Republic", code: "DO", coordinate: CLLocationCoordinate2D(latitude: 18.7357, longitude: -70.1627)),
    CountryLocation(name: "Ecuador", code: "EC", coordinate: CLLocationCoordinate2D(latitude: -1.8312, longitude: -78.1834)),
    CountryLocation(name: "Egypt", code: "EG", coordinate: CLLocationCoordinate2D(latitude: 26.8201, longitude: 30.8025)),
    CountryLocation(name: "El Salvador", code: "SV", coordinate: CLLocationCoordinate2D(latitude: 13.7942, longitude: -88.8965)),
    CountryLocation(name: "Equatorial Guinea", code: "GQ", coordinate: CLLocationCoordinate2D(latitude: 1.6508, longitude: 10.2679)),
    CountryLocation(name: "Eritrea", code: "ER", coordinate: CLLocationCoordinate2D(latitude: 15.1794, longitude: 39.7823)),
    CountryLocation(name: "Estonia", code: "EE", coordinate: CLLocationCoordinate2D(latitude: 58.5953, longitude: 25.0136)),
    CountryLocation(name: "Swaziland", code: "SZ", coordinate: CLLocationCoordinate2D(latitude: -26.5225, longitude: 31.4659)),
    CountryLocation(name: "Ethiopia", code: "ET", coordinate: CLLocationCoordinate2D(latitude: 9.145, longitude: 40.4897)),
    CountryLocation(name: "Fiji", code: "FJ", coordinate: CLLocationCoordinate2D(latitude: -16.5782, longitude: 179.4144)),
    CountryLocation(name: "Finland", code: "FI", coordinate: CLLocationCoordinate2D(latitude: 61.9241, longitude: 25.7482)),
    CountryLocation(name: "France", code: "FR", coordinate: CLLocationCoordinate2D(latitude: 46.6034, longitude: 1.8883)),
    CountryLocation(name: "Gabon", code: "GA", coordinate: CLLocationCoordinate2D(latitude: -0.8037, longitude: 11.6094)),
    CountryLocation(name: "Gambia", code: "GM", coordinate: CLLocationCoordinate2D(latitude: 13.4432, longitude: -15.3101)),
    CountryLocation(name: "Georgia", code: "GE", coordinate: CLLocationCoordinate2D(latitude: 42.3154, longitude: 43.3569)),
    CountryLocation(name: "Germany", code: "DE", coordinate: CLLocationCoordinate2D(latitude: 51.1657, longitude: 10.4515)),
    CountryLocation(name: "Ghana", code: "GH", coordinate: CLLocationCoordinate2D(latitude: 7.9465, longitude: -1.0232)),
    CountryLocation(name: "Greece", code: "GR", coordinate: CLLocationCoordinate2D(latitude: 39.0742, longitude: 21.8243)),
    CountryLocation(name: "Grenada", code: "GD", coordinate: CLLocationCoordinate2D(latitude: 12.2628, longitude: -61.6042)),
    CountryLocation(name: "Guatemala", code: "GT", coordinate: CLLocationCoordinate2D(latitude: 15.7835, longitude: -90.2308)),
    CountryLocation(name: "Guinea", code: "GN", coordinate: CLLocationCoordinate2D(latitude: 9.9456, longitude: -9.6966)),
    CountryLocation(name: "Guinea-Bissau", code: "GW", coordinate: CLLocationCoordinate2D(latitude: 11.8037, longitude: -15.1804)),
    CountryLocation(name: "Guyana", code: "GY", coordinate: CLLocationCoordinate2D(latitude: 4.8604, longitude: -58.9302)),
    CountryLocation(name: "Haiti", code: "HT", coordinate: CLLocationCoordinate2D(latitude: 18.9712, longitude: -72.2852)),
    CountryLocation(name: "Honduras", code: "HN", coordinate: CLLocationCoordinate2D(latitude: 13.9094, longitude: -83.4287)),
    CountryLocation(name: "Hungary", code: "HU", coordinate: CLLocationCoordinate2D(latitude: 47.1625, longitude: 19.5033)),
    CountryLocation(name: "Iceland", code: "IS", coordinate: CLLocationCoordinate2D(latitude: 64.9631, longitude: -19.0208)),
    CountryLocation(name: "India", code: "IN", coordinate: CLLocationCoordinate2D(latitude: 20.5937, longitude: 78.9629)),
    CountryLocation(name: "Indonesia", code: "ID", coordinate: CLLocationCoordinate2D(latitude: -0.7893, longitude: 113.9213)),
    CountryLocation(name: "Iran", code: "IR", coordinate: CLLocationCoordinate2D(latitude: 32.4279, longitude: 53.6880)),
    CountryLocation(name: "Iraq", code: "IQ", coordinate: CLLocationCoordinate2D(latitude: 33.2232, longitude: 43.6793)),
    CountryLocation(name: "Ireland", code: "IE", coordinate: CLLocationCoordinate2D(latitude: 53.4129, longitude: -8.2439)),
    CountryLocation(name: "Israel", code: "IL", coordinate: CLLocationCoordinate2D(latitude: 31.0461, longitude: 34.8516)),
    CountryLocation(name: "Italy", code: "IT", coordinate: CLLocationCoordinate2D(latitude: 42, longitude: 14.5674)),
    CountryLocation(name: "Ivory Coast", code: "CI", coordinate: CLLocationCoordinate2D(latitude: 7.5395, longitude: -5.5471)),
    CountryLocation(name: "Jamaica", code: "JM", coordinate: CLLocationCoordinate2D(latitude: 18.1096, longitude: -77.2975)),
    CountryLocation(name: "Japan", code: "JP", coordinate: CLLocationCoordinate2D(latitude: 36.2048, longitude: 138.2529)),
    CountryLocation(name: "Jordan", code: "JO", coordinate: CLLocationCoordinate2D(latitude: 30.5852, longitude: 36.2384)),
    CountryLocation(name: "Kazakhstan", code: "KZ", coordinate: CLLocationCoordinate2D(latitude: 48.0196, longitude: 66.9237)),
    CountryLocation(name: "Kenya", code: "KE", coordinate: CLLocationCoordinate2D(latitude: -1.2921, longitude: 36.8219)),
    CountryLocation(name: "Kiribati", code: "KI", coordinate: CLLocationCoordinate2D(latitude: -3.3704, longitude: -168.7340)),
    CountryLocation(name: "Kuwait", code: "KW", coordinate: CLLocationCoordinate2D(latitude: 29.3759, longitude: 47.9774)),
    CountryLocation(name: "Kyrgyzstan", code: "KG", coordinate: CLLocationCoordinate2D(latitude: 41.2044, longitude: 74.7661)),
    CountryLocation(name: "Laos", code: "LA", coordinate: CLLocationCoordinate2D(latitude: 19.8563, longitude: 102.4955)),
    CountryLocation(name: "Latvia", code: "LV", coordinate: CLLocationCoordinate2D(latitude: 56.8796, longitude: 24.6032)),
    CountryLocation(name: "Lebanon", code: "LB", coordinate: CLLocationCoordinate2D(latitude: 33.8547, longitude: 35.8623)),
    CountryLocation(name: "Lesotho", code: "LS", coordinate: CLLocationCoordinate2D(latitude: -29.6091, longitude: 28.2336)),
    CountryLocation(name: "Liberia", code: "LR", coordinate: CLLocationCoordinate2D(latitude: 6.4281, longitude: -9.4295)),
    CountryLocation(name: "Libya", code: "LY", coordinate: CLLocationCoordinate2D(latitude: 26.3351, longitude: 17.2283)),
    CountryLocation(name: "Liechtenstein", code: "LI", coordinate: CLLocationCoordinate2D(latitude: 47.1415, longitude: 9.5215)),
    CountryLocation(name: "Lithuania", code: "LT", coordinate: CLLocationCoordinate2D(latitude: 55.1694, longitude: 23.8813)),
    CountryLocation(name: "Luxembourg", code: "LU", coordinate: CLLocationCoordinate2D(latitude: 49.6117, longitude: 6.13)),
    CountryLocation(name: "Madagascar", code: "MG", coordinate: CLLocationCoordinate2D(latitude: -18.7669, longitude: 46.8691)),
    CountryLocation(name: "Malawi", code: "MW", coordinate: CLLocationCoordinate2D(latitude: -13.2543, longitude: 34.3015)),
    CountryLocation(name: "Malaysia", code: "MY", coordinate: CLLocationCoordinate2D(latitude: 4.2105, longitude: 101.9758)),
    CountryLocation(name: "Maldives", code: "MV", coordinate: CLLocationCoordinate2D(latitude: 3.2028, longitude: 73.2207)),
    CountryLocation(name: "Mali", code: "ML", coordinate: CLLocationCoordinate2D(latitude: 17.5707, longitude: -3.9962)),
    CountryLocation(name: "Malta", code: "MT", coordinate: CLLocationCoordinate2D(latitude: 35.9375, longitude: 14.3754)),
    CountryLocation(name: "Marshall Islands", code: "MH", coordinate: CLLocationCoordinate2D(latitude: 7.1315, longitude: 171.1842)),
    CountryLocation(name: "Mauritania", code: "MR", coordinate: CLLocationCoordinate2D(latitude: 21.0079, longitude: -10.9400)),
    CountryLocation(name: "Mauritius", code: "MU", coordinate: CLLocationCoordinate2D(latitude: -20.348404, longitude: 57.5522)),
    CountryLocation(name: "Mexico", code: "MX", coordinate: CLLocationCoordinate2D(latitude: 23.6345, longitude: -102.5528)),
    CountryLocation(name: "Micronesia", code: "FM", coordinate: CLLocationCoordinate2D(latitude: 6.7428, longitude: 158.2150)),
    CountryLocation(name: "Moldova", code: "MD", coordinate: CLLocationCoordinate2D(latitude: 47.4116, longitude: 28.3699)),
    CountryLocation(name: "Monaco", code: "MC", coordinate: CLLocationCoordinate2D(latitude: 43.7333, longitude: 7.4167)),
    CountryLocation(name: "Mongolia", code: "MN", coordinate: CLLocationCoordinate2D(latitude: 46.8625, longitude: 103.8467)),
    CountryLocation(name: "Montenegro", code: "ME", coordinate: CLLocationCoordinate2D(latitude: 42.4411, longitude: 19.2636)),
    CountryLocation(name: "Morocco", code: "MA", coordinate: CLLocationCoordinate2D(latitude: 31.7917, longitude: -7.0926)),
    CountryLocation(name: "Mozambique", code: "MZ", coordinate: CLLocationCoordinate2D(latitude: -18.6657, longitude: 35.5296)),
    CountryLocation(name: "Myanmar", code: "MM", coordinate: CLLocationCoordinate2D(latitude: 21.9139, longitude: 95.9560)),
    CountryLocation(name: "Namibia", code: "NA", coordinate: CLLocationCoordinate2D(latitude: -22.9576, longitude: 18.4904)),
    CountryLocation(name: "Nauru", code: "NR", coordinate: CLLocationCoordinate2D(latitude: -0.5228, longitude: 166.9315)),
    CountryLocation(name: "Nepal", code: "NP", coordinate: CLLocationCoordinate2D(latitude: 28.3949, longitude: 84.1240)),
    CountryLocation(name: "Netherlands", code: "NL", coordinate: CLLocationCoordinate2D(latitude: 52.3676, longitude: 4.9041)),
    CountryLocation(name: "New Zealand", code: "NZ", coordinate: CLLocationCoordinate2D(latitude: -40.9006, longitude: 174.8860)),
    CountryLocation(name: "Nicaragua", code: "NI", coordinate: CLLocationCoordinate2D(latitude: 12.8654, longitude: -85.2072)),
    CountryLocation(name: "Niger", code: "NE", coordinate: CLLocationCoordinate2D(latitude: 17.6078, longitude: 8.0817)),
    CountryLocation(name: "Nigeria", code: "NG", coordinate: CLLocationCoordinate2D(latitude: 9.0820, longitude: 8.6753)),
    CountryLocation(name: "North Korea", code: "KP", coordinate: CLLocationCoordinate2D(latitude: 40.3399, longitude: 127.5101)),
    CountryLocation(name: "North Macedonia", code: "MK", coordinate: CLLocationCoordinate2D(latitude: 41.6086, longitude: 21.7453)),
    CountryLocation(name: "Norway", code: "NO", coordinate: CLLocationCoordinate2D(latitude: 60.4720, longitude: 8.4689)),
    CountryLocation(name: "Oman", code: "OM", coordinate: CLLocationCoordinate2D(latitude: 21.5126, longitude: 55.9231)),
    CountryLocation(name: "Palau", code: "PW", coordinate: CLLocationCoordinate2D(latitude: 7.5149, longitude: 134.5825)),
    CountryLocation(name: "Palestine", code: "PS", coordinate: CLLocationCoordinate2D(latitude: 31.9522, longitude: 35.2332)),
    CountryLocation(name: "Panama", code: "PA", coordinate: CLLocationCoordinate2D(latitude: 8.5375, longitude: -80.7821)),
    CountryLocation(name: "Papua New Guinea", code: "PG", coordinate: CLLocationCoordinate2D(latitude: -6.314993, longitude: 143.9555)),
    CountryLocation(name: "Paraguay", code: "PY", coordinate: CLLocationCoordinate2D(latitude: -23.4425, longitude: -58.4438)),
    CountryLocation(name: "Peru", code: "PE", coordinate: CLLocationCoordinate2D(latitude: -9.19, longitude: -75.0152)),
    CountryLocation(name: "Philippines", code: "PH", coordinate: CLLocationCoordinate2D(latitude: 12.8797, longitude: 121.7740)),
    CountryLocation(name: "Poland", code: "PL", coordinate: CLLocationCoordinate2D(latitude: 51.9194, longitude: 19.1451)),
    CountryLocation(name: "Portugal", code: "PT", coordinate: CLLocationCoordinate2D(latitude: 39.3999, longitude: -8.2245)),
    CountryLocation(name: "Qatar", code: "QA", coordinate: CLLocationCoordinate2D(latitude: 25.3548, longitude: 51.1839)),
    CountryLocation(name: "Romania", code: "RO", coordinate: CLLocationCoordinate2D(latitude: 45.9432, longitude: 24.9668)),
    CountryLocation(name: "Russia", code: "RU", coordinate: CLLocationCoordinate2D(latitude: 55.7558, longitude: 37.6173)),
    CountryLocation(name: "Rwanda", code: "RW", coordinate: CLLocationCoordinate2D(latitude: -1.9403, longitude: 29.8739)),
    CountryLocation(name: "Saint Kitts and Nevis", code: "KN", coordinate: CLLocationCoordinate2D(latitude: 17.3576, longitude: -62.7834)),
    CountryLocation(name: "Saint Lucia", code: "LC", coordinate: CLLocationCoordinate2D(latitude: 13.9094, longitude: -60.9785)),
    CountryLocation(name: "Saint Vincent and the Grenadines", code: "VC", coordinate: CLLocationCoordinate2D(latitude: 12.9843, longitude: -61.2872)),
    CountryLocation(name: "Samoa", code: "WS", coordinate: CLLocationCoordinate2D(latitude: -13.7590, longitude: -172.1046)),
    CountryLocation(name: "San Marino", code: "SM", coordinate: CLLocationCoordinate2D(latitude: 43.9333, longitude: 12.45)),
    CountryLocation(name: "Sao Tome and Principe", code: "ST", coordinate: CLLocationCoordinate2D(latitude: 0.1864, longitude: 6.6131)),
    CountryLocation(name: "Saudi Arabia", code: "SA", coordinate: CLLocationCoordinate2D(latitude: 23.8859, longitude: 45.0792)),
    CountryLocation(name: "Senegal", code: "SN", coordinate: CLLocationCoordinate2D(latitude: 14.6928, longitude: -14.0079)),
    CountryLocation(name: "Serbia", code: "RS", coordinate: CLLocationCoordinate2D(latitude: 44.0165, longitude: 21.0059)),
    CountryLocation(name: "Seychelles", code: "SC", coordinate: CLLocationCoordinate2D(latitude: -4.6796, longitude: 55.4920)),
    CountryLocation(name: "Sierra Leone", code: "SL", coordinate: CLLocationCoordinate2D(latitude: 8.4606, longitude: -11.7799)),
    CountryLocation(name: "Singapore", code: "SG", coordinate: CLLocationCoordinate2D(latitude: 1.3521, longitude: 103.8198)),
    CountryLocation(name: "Slovakia", code: "SK", coordinate: CLLocationCoordinate2D(latitude: 48.6690, longitude: 19.6990)),
    CountryLocation(name: "Slovenia", code: "SI", coordinate: CLLocationCoordinate2D(latitude: 46.1512, longitude: 14.9955)),
    CountryLocation(name: "Solomon Islands", code: "SB", coordinate: CLLocationCoordinate2D(latitude: -29.6091, longitude: 28.2336)),
    CountryLocation(name: "Somalia", code: "SO", coordinate: CLLocationCoordinate2D(latitude: 5.1521, longitude: 46.1996)),
    CountryLocation(name: "South Africa", code: "ZA", coordinate: CLLocationCoordinate2D(latitude: -30.5595, longitude: 22.9375)),
    CountryLocation(name: "South Korea", code: "KR", coordinate: CLLocationCoordinate2D(latitude: 35.9078, longitude: 127.7669)),
    CountryLocation(name: "South Sudan", code: "SS", coordinate: CLLocationCoordinate2D(latitude: 6.8777, longitude: 31.3070)),
    CountryLocation(name: "Spain", code: "ES", coordinate: CLLocationCoordinate2D(latitude: 40.4637, longitude: -3.7492)),
    CountryLocation(name: "Sri Lanka", code: "LK", coordinate: CLLocationCoordinate2D(latitude: 7.8731, longitude: 80.7718)),
    CountryLocation(name: "Sudan", code: "SD", coordinate: CLLocationCoordinate2D(latitude: 12.8628, longitude: 30.2176)),
    CountryLocation(name: "Suriname", code: "SR", coordinate: CLLocationCoordinate2D(latitude: 3.9193, longitude: -56.0278)),
    CountryLocation(name: "Sweden", code: "SE", coordinate: CLLocationCoordinate2D(latitude: 60.1282, longitude: 18.6435)),
    CountryLocation(name: "Switzerland", code: "CH", coordinate: CLLocationCoordinate2D(latitude: 46.8182, longitude: 8.2275)),
    CountryLocation(name: "Syria", code: "SY", coordinate: CLLocationCoordinate2D(latitude: 34.8021, longitude: 38.9968)),
    CountryLocation(name: "Taiwan", code: "TW", coordinate: CLLocationCoordinate2D(latitude: 23.6978, longitude: 120.9605)),
    CountryLocation(name: "Tajikistan", code: "TJ", coordinate: CLLocationCoordinate2D(latitude: 38.8610, longitude: 71.2761)),
    CountryLocation(name: "Tanzania", code: "TZ", coordinate: CLLocationCoordinate2D(latitude: -6.369028, longitude: 34.888822)),
    CountryLocation(name: "Thailand", code: "TH", coordinate: CLLocationCoordinate2D(latitude: 15.8700, longitude: 100.9925)),
    CountryLocation(name: "Timor-Leste", code: "TL", coordinate: CLLocationCoordinate2D(latitude: -8.8742, longitude: 125.7275)),
    CountryLocation(name: "Togo", code: "TG", coordinate: CLLocationCoordinate2D(latitude: 8.6195, longitude: 0.8248)),
    CountryLocation(name: "Tonga", code: "TO", coordinate: CLLocationCoordinate2D(latitude: -21.1789, longitude: -175.1982)),
    CountryLocation(name: "Trinidad and Tobago", code: "TT", coordinate: CLLocationCoordinate2D(latitude: 10.6918, longitude: -61.2225)),
    CountryLocation(name: "Tunisia", code: "TN", coordinate: CLLocationCoordinate2D(latitude: 33.8869, longitude: 9.5375)),
    CountryLocation(name: "Turkey", code: "TR", coordinate: CLLocationCoordinate2D(latitude: 38.9637, longitude: 35.2433)),
    CountryLocation(name: "Turkmenistan", code: "TM", coordinate: CLLocationCoordinate2D(latitude: 38.9697, longitude: 59.5563)),
    CountryLocation(name: "Tuvalu", code: "TV", coordinate: CLLocationCoordinate2D(latitude: -7.1095, longitude: 177.6493)),
    CountryLocation(name: "Uganda", code: "UG", coordinate: CLLocationCoordinate2D(latitude: 1.3733, longitude: 32.2903)),
    CountryLocation(name: "Ukraine", code: "UA", coordinate: CLLocationCoordinate2D(latitude: 48.3794, longitude: 31.1656)),
    CountryLocation(name: "United Kingdom", code: "GB", coordinate: CLLocationCoordinate2D(latitude: 55.3781, longitude: -3.4360)),
    CountryLocation(name: "United States", code: "US", coordinate: CLLocationCoordinate2D(latitude: 37.0902, longitude: -95.7129)),
    CountryLocation(name: "Uruguay", code: "UY", coordinate: CLLocationCoordinate2D(latitude: -32.9659, longitude: -56.2038)),
    CountryLocation(name: "Uzbekistan", code: "UZ", coordinate: CLLocationCoordinate2D(latitude: 41.3775, longitude: 64.5853)),
    CountryLocation(name: "Vanuatu", code: "VU", coordinate: CLLocationCoordinate2D(latitude: -15.3767, longitude: 166.9592)),
    CountryLocation(name: "Vatican City", code: "VA", coordinate: CLLocationCoordinate2D(latitude: 41.9029, longitude: 12.4534)),
    CountryLocation(name: "Venezuela", code: "VE", coordinate: CLLocationCoordinate2D(latitude: 6.4238, longitude: -66.5897)),
    CountryLocation(name: "Vietnam", code: "VN", coordinate: CLLocationCoordinate2D(latitude: 14.0583, longitude: 108.2772)),
    CountryLocation(name: "Yemen", code: "YE", coordinate: CLLocationCoordinate2D(latitude: 15.5525, longitude: 48.5164)),
    CountryLocation(name: "Zambia", code: "ZM", coordinate: CLLocationCoordinate2D(latitude: -13.1339, longitude: 27.8493)),
    CountryLocation(name: "Zimbabwe", code: "ZW", coordinate: CLLocationCoordinate2D(latitude: -19.0154, longitude: 29.1549))
]                                                                             
